# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Install libreoffice
      run: |
        sudo apt-get update
        sudo apt-get install libreoffice
        sudo ln -s /usr/lib/libreoffice /usr/lib/openoffice      
    - name: maven-settings
      uses: s4u/maven-settings-action@v2
      with:
        servers: '[{"id": "edirom", "username": "vifebot", "password": "${GITHUB_TOKEN}"},{"id": "teic", "username": "vifebot", "password": "${GITHUB_TOKEN}"}]'
    - name: Build with Maven
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: mvn -B package --file pom.xml
    - name: Upload Maven build artifact
      uses: actions/upload-artifact@v2
      with:
        name: oo-converter-1.0.jar
        path: /home/runner/work/oo-converter/oo-converter/target/oo-converter-1.0.jar
